/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hanoi;

//import Elementos.PanelTorre;
import java.awt.Color;
import static java.awt.Color.black;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Henry Hrra
 */
public class UI_Hanoi extends javax.swing.JFrame {

    PanelTorre Panel_TorreA;
    PanelTorre Panel_TorreB;
    PanelTorre Panel_TorreC;
    int ContadorMov, Seleccionado;
    int y_ArosA, y_ArosB, y_ArosC;
    boolean y = false;

    //Random rand = new Random();
    /**
     * Creates new form UI
     */
    public UI_Hanoi() {
        initComponents();
        this.Panel_TorreA = new PanelTorre("src/Imagenes/torre.png");
        this.Panel_TorreA.setBounds(6, 70, 150, 180);
        this.Panel_TorreA.setLayout(null);
        //this.Panel_TorreA.setBorder(BorderFactory.createLineBorder(Color.black));
        this.add(Panel_TorreA);

        this.Panel_TorreB = new PanelTorre("src/Imagenes/torre.png");
        this.Panel_TorreB.setBounds(168, 70, 150, 180);
        this.Panel_TorreB.setLayout(null);
        this.add(Panel_TorreB);

        this.Panel_TorreC = new PanelTorre("src/Imagenes/torre.png");
        this.Panel_TorreC.setBounds(330, 70, 150, 180);
        this.Panel_TorreC.setLayout(null);
        this.add(Panel_TorreC);

        this.repaint();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.darkGray);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Empezar = new javax.swing.JButton();
        NunAros = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Button_PB_A = new javax.swing.JButton();
        Button_PB_C = new javax.swing.JButton();
        Button_PC_B = new javax.swing.JButton();
        Button_PC_A = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        N_Mov = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXT_MovHechos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Button_A_B = new javax.swing.JButton();
        Button_Salir = new javax.swing.JButton();
        Button_Instrucciones = new javax.swing.JButton();
        Button_A_C = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        Boton_Empezar.setBackground(new java.awt.Color(60, 110, 113));
        Boton_Empezar.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Boton_Empezar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Empezar.setText("Empezar");
        Boton_Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EmpezarActionPerformed(evt);
            }
        });

        NunAros.setBackground(new java.awt.Color(60, 110, 113));
        NunAros.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        NunAros.setForeground(new java.awt.Color(255, 255, 255));
        NunAros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número de Aros:");

        Button_PB_A.setBackground(new java.awt.Color(64, 64, 64));
        Button_PB_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN3.png"))); // NOI18N
        Button_PB_A.setToolTipText("");
        Button_PB_A.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_PB_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PB_AActionPerformed(evt);
            }
        });

        Button_PB_C.setBackground(new java.awt.Color(64, 64, 64));
        Button_PB_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN2.png"))); // NOI18N
        Button_PB_C.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_PB_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PB_CActionPerformed(evt);
            }
        });

        Button_PC_B.setBackground(new java.awt.Color(64, 64, 64));
        Button_PC_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN1.png"))); // NOI18N
        Button_PC_B.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_PC_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PC_BActionPerformed(evt);
            }
        });

        Button_PC_A.setBackground(new java.awt.Color(64, 64, 64));
        Button_PC_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN3.png"))); // NOI18N
        Button_PC_A.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_PC_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PC_AActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de movimientos:");

        N_Mov.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        N_Mov.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movimienotos Hechos:");

        TXT_MovHechos.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("A");
        jLabel4.setPreferredSize(new java.awt.Dimension(32, 27));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("B");
        jLabel5.setPreferredSize(new java.awt.Dimension(32, 27));

        jLabel6.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("C");
        jLabel6.setPreferredSize(new java.awt.Dimension(32, 27));

        Button_A_B.setBackground(new java.awt.Color(64, 64, 64));
        Button_A_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN1.png"))); // NOI18N
        Button_A_B.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_A_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_A_BActionPerformed(evt);
            }
        });

        Button_Salir.setBackground(new java.awt.Color(64, 64, 64));
        Button_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN_Cerrar.png"))); // NOI18N
        Button_Salir.setPreferredSize(new java.awt.Dimension(22, 22));
        Button_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SalirActionPerformed(evt);
            }
        });

        Button_Instrucciones.setBackground(new java.awt.Color(60, 110, 113));
        Button_Instrucciones.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Button_Instrucciones.setForeground(new java.awt.Color(255, 255, 255));
        Button_Instrucciones.setText("Instrucciones");
        Button_Instrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_InstruccionesActionPerformed(evt);
            }
        });

        Button_A_C.setBackground(new java.awt.Color(64, 64, 64));
        Button_A_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BTN2.png"))); // NOI18N
        Button_A_C.setPreferredSize(new java.awt.Dimension(40, 40));
        Button_A_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_A_CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N_Mov, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_MovHechos)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_A_B, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_A_C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(Button_PB_A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Button_PB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_PC_A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_PC_B, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NunAros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Empezar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_Instrucciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_PC_B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_PC_A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Button_A_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_A_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_PB_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Button_PB_A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NunAros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Empezar)
                    .addComponent(Button_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Instrucciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(TXT_MovHechos))
                    .addComponent(N_Mov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EmpezarActionPerformed
        // TODO add your handling code here:
        Iniciar();
    }//GEN-LAST:event_Boton_EmpezarActionPerformed

    private void Iniciar() {
        this.Panel_TorreA.removeAll();
        this.Panel_TorreB.removeAll();
        this.Panel_TorreC.removeAll();
        ContadorMov = 0;
        y_ArosA = 150;
        y_ArosB = 150;
        y_ArosC = 150;
        y = false;
        TXT_MovHechos.setForeground(Color.white);
        String seleccionado = (String) NunAros.getSelectedItem();
        Seleccionado = Integer.parseInt(seleccionado);
        CrearAros(Seleccionado);
    }

    private void CrearAros(int NumAros) {
        int w = 130;
        int x = 10;
        //Aros Aro;
        //int randomNum;
        for (int contador = 0; contador < NumAros; contador++) {
            //randomNum = ThreadLocalRandom.current().nextInt(0, 5) + 1;
            JLabel Aros = new JLabel();
            Aros.setBounds(x, y_ArosA, w, 15);
            Aros.setVerticalAlignment(JLabel.CENTER);
            Aros.setVisible(true);

            Image img = new ImageIcon("src/Imagenes/Aro.png").getImage();
            ImageIcon img2 = new ImageIcon(img.getScaledInstance(w, 15, Image.SCALE_SMOOTH));
            Aros.setIcon(img2);

            //Aro = new Aros(x,w,y_ArosA);
            this.Panel_TorreA.add(Aros);

            Panel_TorreA.updateUI();
            Panel_TorreB.updateUI();
            Panel_TorreC.updateUI();
            y_ArosA = y_ArosA - 15;
            w = w - 10;
            x = x + 5;
        }
        int m;
        m = (int) (Math.pow(2, NumAros) - 1);
        N_Mov.setText(m + "");
        TXT_MovHechos.setText(ContadorMov + "");
    }

    private void Button_PB_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PB_AActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreB, Panel_TorreA, y_ArosA));
            Panel_TorreB = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreA = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreB.updateUI();
            Panel_TorreA.updateUI();
            if (y == true) {
                y_ArosA = y_ArosA - 15;
                y_ArosB = y_ArosB + 15;
            }
            //  Block of code to try
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_PB_AActionPerformed

    private void Button_PB_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PB_CActionPerformed
        // TODO add your handling code here:
        try {
            //  Block of code to try
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreB, Panel_TorreC, y_ArosC));
            Panel_TorreB = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreC = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreB.updateUI();
            Panel_TorreC.updateUI();
            if (y == true) {
                y_ArosC = y_ArosC - 15;
                y_ArosB = y_ArosB + 15;
            }
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_PB_CActionPerformed

    private void Button_PC_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PC_AActionPerformed
        // TODO add your handling code here:
        try {
            //  Block of code to try
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreC, Panel_TorreA, y_ArosA));
            Panel_TorreC = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreA = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreC.updateUI();
            Panel_TorreA.updateUI();
            if (y == true) {
                y_ArosA = y_ArosA - 15;
                y_ArosC = y_ArosC + 15;
            }
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_PC_AActionPerformed

    private void Button_PC_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PC_BActionPerformed
        // TODO add your handling code here:
        try {
            //  Block of code to try
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreC, Panel_TorreB, y_ArosB));
            Panel_TorreC = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreB = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreC.updateUI();
            Panel_TorreB.updateUI();
            if (y == true) {
                y_ArosB = y_ArosB - 15;
                y_ArosC = y_ArosC + 15;
            }
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_PC_BActionPerformed

    private void Button_A_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_A_BActionPerformed
        // TODO add your handling code here:
        try {
            //  Block of code to try
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreA, Panel_TorreB, y_ArosB));
            Panel_TorreA = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreB = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreA.updateUI();
            Panel_TorreB.updateUI();
            if (y == true) {
                y_ArosB = y_ArosB - 15;
                y_ArosA = y_ArosA + 15;
            }
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_A_BActionPerformed

    private void Button_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Button_SalirActionPerformed

    private void Button_InstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_InstruccionesActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        UI_Instrucciones abrir = new UI_Instrucciones();
        abrir.setVisible(true);
    }//GEN-LAST:event_Button_InstruccionesActionPerformed

    private void Button_A_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_A_CActionPerformed
        // TODO add your handling code here:
        try {
            //  Block of code to try
            ArrayList<Component> panels = new ArrayList();
            panels.addAll(moverAros(Panel_TorreA, Panel_TorreC, y_ArosC));
            Panel_TorreA = (PanelTorre) (JPanel) panels.get(0);
            Panel_TorreC = (PanelTorre) (JPanel) panels.get(1);
            Panel_TorreA.updateUI();
            Panel_TorreC.updateUI();
            if (y == true) {
                y_ArosC = y_ArosC - 15;
                y_ArosA = y_ArosA + 15;
            }
        } catch (Exception e) {
            //  Block of code to handle errors
        }
    }//GEN-LAST:event_Button_A_CActionPerformed

    public void contador(int NumAros) {
        //String seleccionado = (String) NunAros.getSelectedItem();
        ContadorMov++;
        TXT_MovHechos.setText(ContadorMov + "");
        if (ContadorMov > Integer.parseInt(N_Mov.getText())) {
            TXT_MovHechos.setForeground(Color.red);
        }
        if ((ContadorMov == Integer.parseInt(N_Mov.getText())) && (NumAros == (Panel_TorreC.getComponentCount()))) {
            JOptionPane.showMessageDialog(null, "Felicidades");
        }
    }

    private ArrayList moverAros(JPanel Pasa, JPanel Recibe, int y_Recibe) {
        ArrayList<Component> panels = new ArrayList();
        int arosA, arosB;
        try {
            if (Recibe.getComponentCount() < 1) {
                Component[] labels = Pasa.getComponents();
                arosA = labels.length - 1;
                labels[arosA].setBounds(labels[arosA].getX(), y_Recibe, labels[arosA].getWidth(), labels[arosA].getHeight());
                Recibe.add(labels[arosA]);
                panels.add(Pasa);
                panels.add(Recibe);
                contador(Seleccionado);
                y = true;
            } else {
                Component[] labelsA = Pasa.getComponents();
                Component[] labelsB = Recibe.getComponents();
                arosA = labelsA.length - 1;
                arosB = labelsB.length - 1;
                if (labelsB[arosB].getWidth() < labelsA[arosA].getWidth()) {
                    JOptionPane.showMessageDialog(null, "No puede colocar una anillo mas grande sobre uno mas pequeño");
                    panels.add(Pasa);
                    panels.add(Recibe);
                    y = false;
                } else {
                    labelsA[arosA].setBounds(labelsA[arosA].getX(), y_Recibe, labelsA[arosA].getWidth(), labelsA[arosA].getHeight());
                    Recibe.add(labelsA[arosA]);
                    panels.add(Pasa);
                    panels.add(Recibe);
                    contador(Seleccionado);
                    y = true;
                }
            }

        } catch (Exception e) {

        }

        return panels;
    }
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Hanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Hanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Hanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Hanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Hanoi().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Empezar;
    private javax.swing.JButton Button_A_B;
    private javax.swing.JButton Button_A_C;
    private javax.swing.JButton Button_Instrucciones;
    private javax.swing.JButton Button_PB_A;
    private javax.swing.JButton Button_PB_C;
    private javax.swing.JButton Button_PC_A;
    private javax.swing.JButton Button_PC_B;
    private javax.swing.JButton Button_Salir;
    private javax.swing.JLabel N_Mov;
    private javax.swing.JComboBox<String> NunAros;
    private javax.swing.JLabel TXT_MovHechos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
